// svelte-typescript-vite/src/lib/CircleDrawer.svelte
<!--
https://eugenkiss.github.io/7guis/tasks#circle

Click on the canvas to draw a circle. Click on a circle
to select it. Right-click on the canvas to adjust the
radius of the selected circle.
-->
<script>
  let i = 0;
  let undoStack = [[]];
  let circles = [];
  let selected;
  let adjusting = false;
  let adjusted = false;

  function handleClick(event) {
    if (adjusting) {
      adjusting = false;

      // if circle was adjusted,
      // push to the stack
      if (adjusted) push();
      return;
    }

    const circle = {
      cx: event.clientX,
      cy: event.clientY,
      r: 50,
    };

    circles = circles.concat(circle);
    selected = circle;

    push();
  }

  function adjust(event) {
    selected.r = +event.target.value;
    circles = circles;
    adjusted = true;
  }

  function select(circle, event) {
    if (!adjusting) {
      event.stopPropagation();
      selected = circle;
    }
  }

  function push() {
    const newUndoStack = undoStack.slice(0, ++i);
    newUndoStack.push(clone(circles));
    undoStack = newUndoStack;
  }

  function travel(d) {
    circles = clone(undoStack[(i += d)]);
    adjusting = false;
  }

  function clone(circles) {
    return circles.map(({ cx, cy, r }) => ({ cx, cy, r }));
  }
</script>

<div class="controls">
  <button on:click={() => travel(-1)} disabled={i === 0}>undo</button>
  <button on:click={() => travel(+1)} disabled={i === undoStack.length - 1}
    >redo</button
  >
</div>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<svg on:click={handleClick}>
  {#each circles as circle}
    <circle
      cx={circle.cx}
      cy={circle.cy}
      r={circle.r}
      on:click={(event) => select(circle, event)}
      on:contextmenu|stopPropagation|preventDefault={() => {
        adjusting = !adjusting;
        if (adjusting) selected = circle;
      }}
      fill={circle === selected ? "#ccc" : "white"}
    />
  {/each}
</svg>

{#if adjusting}
  <div class="adjuster">
    <p>adjust diameter of circle at {selected.cx}, {selected.cy}</p>
    <input type="range" value={selected.r} on:input={adjust} />
  </div>
{/if}

<style>
  .controls {
    position: absolute;
    width: 100%;
    text-align: center;
  }

  svg {
    background-color: #eee;
    width: 100%;
    height: 100%;
  }

  circle {
    stroke: black;
  }

  .adjuster {
    position: absolute;
    width: 80%;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    padding: 1em;
    text-align: center;
    background-color: rgba(255, 255, 255, 0.7);
    border-radius: 4px;
  }

  input[type="range"] {
    width: 100%;
  }
</style>

// vue-typescript-vite/src/components/CircleDrawer.vue
<!--
https://eugenkiss.github.io/7guis/tasks/#circle
-->

<script>
function clone(circles) {
  return circles.map((c) => ({ ...c }))
}

export default {
  data() {
    return {
      history: [[]],
      index: 0,
      circles: [],
      selected: null,
      adjusting: false
    }
  },
  methods: {
    onClick({ clientX: x, clientY: y }) {
      if (this.adjusting) {
        this.adjusting = false
        this.selected = null
        this.push()
        return
      }

      this.selected = [...this.circles].reverse().find(({ cx, cy, r }) => {
        const dx = cx - x
        const dy = cy - y
        return Math.sqrt(dx * dx + dy * dy) <= r
      })

      if (!this.selected) {
        this.circles.push({
          cx: x,
          cy: y,
          r: 50
        })
        this.push()
      }
    },

    adjust(circle) {
      this.selected = circle
      this.adjusting = true
    },

    push() {
      this.history.length = ++this.index
      this.history.push(clone(this.circles))
    },

    undo() {
      this.circles = clone(this.history[--this.index])
    },

    redo() {
      this.circles = clone(this.history[++this.index])
    }
  }
}
</script>

<template>
  <svg @click="onClick">
    <foreignObject x="0" y="40%" width="100%" height="200">
      <p class="tip">
        Click on the canvas to draw a circle. Click on a circle to select it.
        Right-click on the canvas to adjust the radius of the selected circle.
      </p>
    </foreignObject>
    <circle
      v-for="circle in circles"
      :cx="circle.cx"
      :cy="circle.cy"
      :r="circle.r"
      :fill="circle === selected ? '#ccc' : '#fff'"
      @click="selected = circle"
      @contextmenu.prevent="adjust(circle)"
    ></circle>
  </svg>

  <div class="controls">
    <button @click="undo" :disabled="index <= 0">Undo</button>
    <button @click="redo" :disabled="index >= history.length - 1">Redo</button>
  </div>

  <div class="dialog" v-if="adjusting" @click.stop>
    <p>Adjust radius of circle at ({{ selected.cx }}, {{ selected.cy }})</p>
    <input type="range" v-model="selected.r" min="1" max="300">
  </div>
</template>

<style>
body {
  margin: 0;
  overflow: hidden;
}

svg {
  width: 100vw;
  height: 100vh;
  background-color: #eee;
}

circle {
  stroke: #000;
}

.controls {
  position: fixed;
  top: 10px;
  left: 0;
  right: 0;
  text-align: center;
}

.controls button + button {
  margin-left: 6px;
}

.dialog {
  position: fixed;
  top: calc(50% - 50px);
  left: calc(50% - 175px);
  background: #fff;
  width: 350px;
  height: 100px;
  padding: 5px 20px;
  box-sizing: border-box;
  border-radius: 4px;
  text-align: center;
  box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.25);
}

.dialog input {
  display: block;
  width: 200px;
  margin: 0px auto;
}

.tip {
  text-align: center;
  padding: 0 50px;
  color: #bbb;
}
</style>
